name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.12

    - name: Build
      run: ./build.sh

    - name: Test
      run: go test -v ./...

    - name: Create destination directory
      run: mkdir -p path/to/artifact

    - name: Copy artifact to destination directory
      run: cp magicDefault path/to/artifact/magicDefault

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: artifact
        path: path/to/artifact/magicDefault
